### ISSUE TITLE
how to profile nccl kernel  in this project with nsight compute

### ISSUE THREAD

**Issue by Zjhzzzzz** [NVIDIA/FasterTransformer#114]
I try to use ncu profile gpt demo but hangs when profiling  ncclAllReduceKernel, I think all nccl kernel may have this problem.
So, how to solve this problem.
plz.

**Comment by byshiue** [comment]
Can you provide more information? 
What docker image / GPU /  hyper-parameters you use?

**Comment by Zjhzzzzz** [comment]
> Can you provide more information?
> What docker image / GPU / hyper-parameters you use?

nvcr.io/nvidia/tensorrt:20.0 / 8 2080ti /I don't change any parameters / my ncu command is ncu --target-processes all --metrics all --export nsreport -f mpirun -n 8 --allow-run-as-root ./bin/gpt_sample

**Comment by Zjhzzzzz** [comment]
> Can you provide more information?
> What docker image / GPU / hyper-parameters you use?

and when ncu profiling nccl kernel it stop here, I have to ctrl+c kill it

**Comment by byshiue** [comment]
1. Have you tried to run without ncu?
2. Have you tried to run with 1 gpu? 
3. Have you tried to use the docker image we recommend?

**Comment by Zjhzzzzz** [comment]
> * Have you tried to run without ncu?
> * Have you tried to run with 1 gpu?
> * Have you tried to use the docker image we recommend?

I run this demo successfully.
My only problem is about how to profiling this demo with nsight compute because there is problem in profiling nccl kernel.

**Comment by byshiue** [comment]
For the reduction operation of tensor parallel, ncu cannot profile them because ncu serializes the kernel launches across all profiled process, so the kerensl won't be able to make forward progress if it is waiting for other concurrent processes.
If you want to check the performance of these reduction kernels, you can try to use nsight systems.

**Comment by Zjhzzzzz** [comment]
> For the reduction operation of tensor parallel, ncu cannot profile them because ncu serializes the kernel launches across all profiled process, so the kerensl won't be able to make forward progress if it is waiting for other concurrent processes.
> If you want to check the performance of these reduction kernels, you can try to use nsight systems.

thanks for reply, but nsight system can only see timeline without other information
can I profile this demo by skipping nccl kernel? 
In nvidia docs I don't find any information about skip kernel, and use "-k kernel_name" is too inconvenient...

**Comment by byshiue** [comment]
If you want to profile the kernel of GPT, you can profile the kernel on single gpu program, and reduce the head_size of original model to 1/8. 
For example, if you want to understand the performance of GPT-3 model, you can profile 1 gpu with `head_size=12`. You can use this method to profile the kernels of transformer layers.

**Comment by Zjhzzzzz** [comment]
> If you want to profile the kernel of GPT, you can profile the kernel on single gpu program, and reduce the head_size of original model to 1/8.
> For example, if you want to understand the performance of GPT-3 model, you can profile 1 gpu with `head_size=12`. You can use this method to profile the kernels of transformer layers.

thanks for your help, this problem solved and I will close this issue.
