### ISSUE TITLE
nvcr.io/nvidia/pytorch:21.03-py3

### ISSUE THREAD

**Issue by dingjingzhen** [NVIDIA/FasterTransformer#149]
Hi,does it support nvcr.io/nvidia/pytorch:21.03-py3 ?

**Comment by byshiue** [comment]
It should support although we don't verify on all possible docker images. Do yo encounter any problem?

**Comment by dingjingzhen** [comment]
yes,there is a bug when QKV cublasGemmBatchedEx.
 [ERROR] CUDA runtime error: CUBLAS_STATUS_NOT_SUPPORTED
batch_size = 4,seq_len=100,hidden_units=1024.
when i use nvcr.io/nvidia/pytorch:20.12-py3,it is ok.

**Comment by dingjingzhen** [comment]
i think this may be a bug of cublas with cuda 11.2 or pytorch 1.9

**Comment by byshiue** [comment]
There is a new checking in newer cublas, which requires the alignment of pointer of array in cublasGemmBatchedEx. This may possible reason because we use only 3 pointers (weights of qkv) here.

**Comment by dingjingzhen** [comment]
Thanks for your reply, so is there no way to use this fused method on higher versions of cublas? Or how to solve this problem?

**Comment by byshiue** [comment]
You can pad the array of pointer to prevent this issue. We will fix it in next release.

**Comment by dingjingzhen** [comment]
ok，thank you very much.

**Comment by dingjingzhen** [comment]
Hi, sorry, I have another question to ask, is the matrix multiplication of cublasLt faster than the matrix multiplication of cublas at cuda11 and above?

**Comment by byshiue** [comment]
cublasLt is faster than cublas on some cases, but we don't find obvious trend.

**Comment by dingjingzhen** [comment]
Hi, is this problem solved in the latest version of cublas?

**Comment by byshiue** [comment]
I am not sure. You can test on latest cublas.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Feel free to re-open this issue if you still have any problem.
