### ISSUE TITLE
BF16 broken for UL2 in FT v5.1

### ISSUE THREAD

**Issue by michaelroyzen** [NVIDIA/FasterTransformer#307]
### Description

```shell
Running the UL2 tutorial on using bf16 results in an illegal memory access:

Traceback (most recent call last):
  File "../examples/pytorch/t5/summarization.py", line 375, in <module>
    main()
  File "../examples/pytorch/t5/summarization.py", line 282, in main
    summary_ft, _ = summarize_ft(datapoint)
  File "../examples/pytorch/t5/summarization.py", line 235, in summarize_ft
    output, ft_output_len = ft_t5(line_tokens,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/FasterTransformer/examples/pytorch/t5/../../../examples/pytorch/t5/utils/ft_decoding.py", line 355, in forward
    results = self.decoding.forward(beam_size,  # optional, can be None
  File "/home/michael/FasterTransformer/examples/pytorch/t5/../../../examples/pytorch/t5/utils/ft_decoding.py", line 329, in forward
    results = self.decoding.forward(beam_width, max_seq_len,
RuntimeError: [FT][ERROR] CUDA runtime error: an illegal memory access was encountered /home/michael/FasterTransformer/src/fastertransformer/utils/memory_utils.cu:96
```

### Reproduced Steps

```shell
1. Run the nvcr.io/nvidia/pytorch:22.04-py3
2. Follow the UL2 tutorial in the FT v5.1 doc, setting 1 for inference_tensor_para_size instead of 2: https://github.com/NVIDIA/FasterTransformer/blob/main/docs/t5_guide.md#running-ul2-on-fastertransformer-pytorch-op3. 

Here are the two commands that I ran: 

python3 ../examples/pytorch/t5/utils/huggingface_t5_ckpt_convert.py \
        -saved_dir ul2/c-models \
        -in_file google/ul2 \
        -inference_tensor_para_size 1 \
        -weight_data_type fp32

python3 ../examples/pytorch/t5/summarization.py  \
                      --ft_model_location ul2/c-models/ \
                      --hf_model_location google/ul2 \
                      --test_ft \
                      --data_type bf16 \
                      --tensor_para_size 1

The export runs successfully, but summarization.py crashes.

Hardware: 1x NVIDIA A100-80GB
```

**Comment by byshiue** [comment]
Everything works fine on our side. Can you provide more details, including how you build the project, how you convert the ckpt and how to run the program. Also, please compile by `-DCMAKE_BUILD_TYPE=Debug` to get more information.

**Comment by michaelroyzen** [comment]
It was built following the instructions: 
`cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
make`

I copied the make instructions from the page directly. I only replaced -DSM=xx with -DSM=80 for the A100-80GB GPU.

**Comment by byshiue** [comment]
> It was built following the instructions: `cmake -DSM=80 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON .. make`
> 
> I copied the make instructions from the page directly. I only replaced -DSM=xx with -DSM=80 for the A100-80GB GPU.
> 
> Information on how I built and run the program is in the "Reproduced Steps" section above.
> 
> Could you tell me what settings you used to have it work @byshiue?

I use A100-80GB by following the document step by step.

**Comment by michaelroyzen** [comment]
What NVIDIA driver & docker version are you using?

**Comment by byshiue** [comment]
> What NVIDIA driver & docker version are you using?

The docker version is described in the document (pytorch:22.07-py3), and driver is not affected. We have verified on many different driver.

**Comment by michaelroyzen** [comment]
I'm running the document step by step as well. I'm running NVIDIA's pytorch:22.04-py3 container on driver version 510.

It seems that bfloat16 is broken across the board -- the issue occurs with t5v1.1 as well and is easier to reproduce as the model is much smaller than ul2.

Running `python3 ../examples/pytorch/t5/summarization.py  \
        --ft_model_location t5-v1_1-base/c-models/ \
        --hf_model_location t5-v1_1-base/ \
        --test_ft \
        --test_hf`

works just fine, but  adding `--data_type bf16` results in 

> [FT][DEBUG] std::string fastertransformer::IAllocator::getAddress(void*) const
[FT][DEBUG] virtual fastertransformer::Allocator<fastertransformer::AllocatorType::TH>$
:~Allocator()
Traceback (most recent call last):
  File "../examples/pytorch/t5/summarization.py", line 375, in <module>
    main()
  File "../examples/pytorch/t5/summarization.py", line 282, in main
    summary_ft, _ = summarize_ft(datapoint)
  File "../examples/pytorch/t5/summarization.py", line 235, in summarize_ft
    output, ft_output_len = ft_t5(line_tokens,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111,
in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/michael/FasterTransformer/examples/pytorch/t5/../../../examples/pytorch/$
5/utils/ft_decoding.py", line 355, in forward
    results = self.decoding.forward(beam_size,  # optional, can be None
  File "/home/michael/FasterTransformer/examples/pytorch/t5/../../../examples/pytorch/$
5/utils/ft_decoding.py", line 329, in forward
    results = self.decoding.forward(beam_width, max_seq_len,
RuntimeError: [FT][ERROR] CUDA runtime error: an illegal memory access was encountered
/home/michael/FasterTransformer/src/fastertransformer/layers/attention_layers/DecoderC$
ossAttentionLayer.cu:978

[FT][DEBUG] torch_ext::FTT5Encoder<T>::~FTT5Encoder() [with T = __nv_bfloat16]

**Comment by byshiue** [comment]
Fixed in latest FT's code. Please try again.

**Comment by michaelroyzen** [comment]
Great, it's working now. Thanks @byshiue.
