### ISSUE TITLE
When inter_size is not the power of 2 cuda error occurs in multi_gpu_gpt_example

### ISSUE THREAD

**Issue by taehwakkwon** [NVIDIA/FasterTransformer#389]
### Branch/Tag/Commit

release/v5.2_tag/20f6181e743d5df0a271db52475e3ab98c23bdf8

### Docker Image Version

not available to use docker image

### GPU name

A100 x 8

### CUDA Driver

470.103.01

### Reproduced Steps

```shell
I'm trying to inference large gpt model. However some CUDA error occurs in specific situation. Because I am not familar in cuda code, I cannot figure out what the problem is. There are more details as follows.

GPU : A100 x 8
CUDA : cuda11.0.3
PyTorch : v1.12.0(build from source)
GPU Driver : 470.103.01
Error output : [FT][ERROR] CUDA runtime error: too many resources requested for launch src/fastertransformer/layers/FfnLayer.cc:298
Specific situation : inter size > 5000(not sure?) and head_num(or inter_size) is not the power of 2.

examples/cpp/multi_gpu_gpt/gpt_config.ini
...
[self_defined]
head_num=24
size_per_head=64
vocab_size=30000
decoder_layers=1
start_id=1
end_id=2
inter_size=6144 #inter_size is 12288, 24576, ...



$ cmake -DSM=80 -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON ..
$ make -j 128
$ ./bin/multi_gpu_gpt_example
```

Also I have other error at 'https://github.com/NVIDIA/FasterTransformer/blob/main/3rdparty/trt_fused_multihead_attention/fused_multihead_attention_v2.h#L5393'. I checked the kernelMeta.mD which was 144. I couldn't find what the kernelMeta.mD is. So, I just added `|| kernelMeta.mD == 144`. Is this cause for that CUDA error?
```

**Comment by byshiue** [comment]
The issue of 'https://github.com/NVIDIA/FasterTransformer/blob/main/3rdparty/trt_fused_multihead_attention/fused_multihead_attention_v2.h#L5393'. is a bug, we have fixed it. 

For the issue of `inter_size`, there is no limitation for `head_num` and `inter_size`. You can try to compile on release mode and run again.

**Comment by taehwakkwon** [comment]
It works on release mode and also, output looks fine. However, "CUDA Error: (null) /home/sr5/taehwak.kwon/test/FasterTransformer/3rdparty/trt_fused_multihead_attention/fused_multihead_attention.h 232, 38, 33" occurs. All those errors from 'cuErrCheck' function. 

I have one more question. 
Q)How to evaluate FasterTransformer generates right output?
FasterTransformer generates different output compared to Megatron-LM. I checked 'decoder_normed_input_' (ParallelGptDecoder.cc#338) value with Megatron-LM's. The different is up to 6.9 in my checkpoint. The different starts from LayerNorm. So, I was wondering that how to verify FasterTransformer generates right and solid output? 
+Their inference data types are bf16. I can understand bf16's precision is really bad. What I want to know is the way how you evaluates FasterTransformer.

**Comment by byshiue** [comment]
1. The error means that you don't load some kernel successfully. Then the results may be affected. Can you post the scripts you use? 
2. We verify the accuracy / scores on some datasets. You can refer the examples in gpt document.
