### ISSUE TITLE
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by shanekong** [NVIDIA/FasterTransformer#551]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

2080Ti

### CUDA Driver

unkown

### Reproduced Steps

```shell
[INFO] WARNING: Have initialized the process group

Traceback (most recent call last):

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/app.py", line 33, in <module>

inference = Inference(ckpt_path, vob_path, lib_path, tensor_para_size, pipeline_para_size)

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/inference.py", line 68, in __init__

self.gpt = self.load_model(ckpt_path, lib_path, tensor_para_size, pipeline_para_size)

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/inference.py", line 127, in load_model

if not gpt.load(ckpt_path=ckpt_path):

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/gpt.py", line 542, in load

self.cuda()

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/parallel_gpt.py", line 23, in cuda

self.weights._map(lambda w: w.cuda(self.device))

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/gpt.py", line 233, in _map

self.w[i] = func(self.w[i])

File "/root/workspace/FT/FasterTransformer/examples/pytorch/gpt/../../../examples/pytorch/gpt/utils/parallel_gpt.py", line 23, in <lambda>

self.weights._map(lambda w: w.cuda(self.device))

RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
```

**Comment by byshiue** [comment]
Please provide the scripts to reproduce. Don't only show the last few info of back tracing.

**Comment by byshiue** [comment]
> thank you for your reply, i have solved the problem. I am trying to use FT on 2080Ti, the bug arises, when i build the project with -DSM=60 to geneate so. cmake -DSM=60 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON .. make -j12
> 
> I rebuild the so, use -DSM=70, it works on 2080Ti. cmake -DSM=70 -DCMAKE_BUILD_TYPE=Release -DBUILD_PYT=ON -DBUILD_MULTI_GPU=ON .. make -j12

For 2080Ti, you should build with SM=75. 70 may work in most cases, but has potential risk and is not best.
