### ISSUE TITLE
the latest nvidia pytorch image would fail during the compilation

### ISSUE THREAD

**Issue by gyin-ai** [NVIDIA/FasterTransformer#80]
image: `nvidia/pytorch:21.04-py3`

error:
```
-- Found cuDNN: v8.2.0  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Warning at /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:198 (message):
  Failed to compute shorthash for libnvrtc.so
Call Stack (most recent call first):
  /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /opt/conda/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:211 (find_package)
```

**Comment by byshiue** [comment]
Can you try `nvidia/pytorch:20.12-py3`. We have verified the correctness on this docker image.

**Comment by gyin-ai** [comment]
> Can you try `nvidia/pytorch:20.12-py3`. We have verified the correctness on this docker image.

Yes. This image works for me and I can also run the 124M example model successfully with pytorch: gpt_sample.py. However I found that the gpt2 pt op doesn't work for gpt2 model with a different hparams setting, smaller vocabulary size and smaller layer_num. 

The error is also not sufficient to debug. 
```
RuntimeError: [FT][ERROR] CUDA runtime error: CUBLAS_STATUS_INTERNAL_ERROR /workspace/FasterTransformer/fastertransformer/utils/functions.h:674
```

**Comment by gyin-ai** [comment]
can I ask whether we hard code some parameters based on open source gpt2 hparams.json?

**Comment by byshiue** [comment]
Only for convenience becuase all gpt model use same vocab.
